# Generated by Django 4.1.7 on 2023-06-21 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loancredit',
            name='bank_manager',
        ),
        migrations.AlterField(
            model_name='loancredit',
            name='farmer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app1.farmer'),
        ),
        migrations.CreateModel(
            name='LoanCredit2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bank_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.bankmanager')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.farmer')),
            ],
        ),
    ]
