# Generated by Django 4.1.7 on 2023-06-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_farmer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer_user',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Login'),
        ),
    ]
