# Generated by Django 4.1.7 on 2023-06-23 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_assetliability_image_alter_assetliability_car_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetliability',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/', verbose_name='图片上传'),
        ),
    ]
