# Generated by Django 4.1.7 on 2023-06-25 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_businessinfo_business_license'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assetliability',
            options={'verbose_name': '资产负债情况', 'verbose_name_plural': '资产负债情况'},
        ),
        migrations.AlterModelOptions(
            name='businessinfo',
            options={'verbose_name': '经营信息', 'verbose_name_plural': '经营信息'},
        ),
        migrations.AlterModelOptions(
            name='familymember',
            options={'verbose_name': '家庭信息表', 'verbose_name_plural': '家庭信息'},
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'verbose_name': '基本信息表', 'verbose_name_plural': '基本信息'},
        ),
        migrations.AlterModelOptions(
            name='incomeexpense',
            options={'verbose_name': '家庭收支信息', 'verbose_name_plural': '家庭收支信息'},
        ),
        migrations.AddField(
            model_name='farmer',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '未通过')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='agricultural_insurance',
            field=models.BooleanField(verbose_name='是否参保农业保险'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='agricultural_subsidy',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='农业补贴（元/年）'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='awards',
            field=models.CharField(max_length=255, verbose_name='获奖情况'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='business_license',
            field=models.ImageField(blank=True, null=True, upload_to='business/licenses/', verbose_name='营业执照'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='enterprise_name',
            field=models.CharField(max_length=255, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='businessinfo',
            name='production_cycle',
            field=models.CharField(max_length=255, verbose_name='生产经营周期'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='contact',
            field=models.CharField(max_length=20, verbose_name='联系方式'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='id_number',
            field=models.CharField(max_length=18, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='name',
            field=models.CharField(max_length=255, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='familymember',
            name='relationship',
            field=models.CharField(max_length=255, verbose_name='与户主关系'),
        ),
    ]
