# Generated by Django 4.1.7 on 2023-06-25 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_alter_assetliability_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessinformationapproval',
            name='bank_manager',
        ),
        migrations.RemoveField(
            model_name='businessinformationapproval',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='farmerinformationaudit',
            name='bank_manager',
        ),
        migrations.RemoveField(
            model_name='farmerinformationaudit',
            name='farmer',
        ),
        migrations.RemoveField(
            model_name='loancredit2',
            name='bank_manager',
        ),
        migrations.RemoveField(
            model_name='loancredit2',
            name='farmer',
        ),
        migrations.AddField(
            model_name='loancredit',
            name='name',
            field=models.CharField(default=1, max_length=255, verbose_name='姓名'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loancredit',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '已拒绝')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='status',
            field=models.CharField(choices=[('pending', '待审核'), ('approved', '已通过'), ('rejected', '未通过')], default='pending', max_length=10, verbose_name='审核状态'),
        ),
        migrations.AlterField(
            model_name='loancredit',
            name='loan_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='贷款金额'),
        ),
        migrations.DeleteModel(
            name='BankManager',
        ),
        migrations.DeleteModel(
            name='BusinessInformationApproval',
        ),
        migrations.DeleteModel(
            name='FarmerInformationAudit',
        ),
        migrations.DeleteModel(
            name='LoanCredit2',
        ),
    ]
