# Generated by Django 4.1.7 on 2023-06-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_remove_businessinformationapproval_bank_manager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loancredit',
            name='status',
            field=models.CharField(choices=[('待审核', '待审核'), ('已通过', '已通过'), ('未通过', '未通过')], default='pending', max_length=20, verbose_name='审核状态'),
        ),
    ]
